name: Build Dotnet

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0 # At 00:00 on Sunday.
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  BUILD_CONFIG: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
        with:
          restore-wasm-workload: true
          dotnet-version: |
            9.0.x
      - name: dotnet build
        run: dotnet build MathAlgorithm.sln -c ${{ env.BUILD_CONFIG }}
      - name: dotnet run
        run: dotnet run --project ./src/CSharp/MathRunner/MathRunner.csproj -c ${{ env.BUILD_CONFIG }}
